export const PROCESSES_NAME = [
  "open-file",
  "open-buffer",
  "open-bufnr",
  "git-action",
  "git-status",
  "git-status-actions",
  "git-branch",
  "git-branch-actions",
  "git-log",
  "git-log-actions",
  "git-stash",
  "git-stash-actions",
  "register",
  "open-pr",
] as const
