export const PERSIST_LOAD_STORE = "persist/loadStore"
export const PERSIST_LOAD_RESUME = "persist/loadResume"
export const PERSIST_LOAD_SESSION = "persist/loadSession"
export const PERSIST_LOAD_GIT_CONFIG = "persist/loadGitConfig"
export const PERSIST_SAVE_STORE = "persist/saveStore"

export const VIM_VARIABLE = "vim_variable"
export const EXECUTE_COMMAND = "execute_command"
export const CACHE = "cache"
export const RESUME = "resume"
export const SESSION = "session"
export const GIT_CONFIG = "git_config"
