export const vimVariableAssociation = {
  fzfPreviewDefaultFzfOptions: "fzf_preview_default_fzf_options",
  fzfPreviewUseDevIcons: "fzf_preview_use_dev_icons",
  fzfPreviewDevIconPrefixStringLength: "fzf_preview_dev_icon_prefix_string_length",
  fzfPreviewDevIconsLimit: "fzf_preview_dev_icons_limit",
  webDevIconsUnicodeDecorateFileNodesDefaultSymbol: "WebDevIconsUnicodeDecorateFileNodesDefaultSymbol",
  webDevIconsUnicodeDecorateFileNodesExtensionSymbols: "WebDevIconsUnicodeDecorateFileNodesExtensionSymbols",
  webDevIconsUnicodeDecorateFileNodesExactSymbols: "WebDevIconsUnicodeDecorateFileNodesExactSymbols",
  webDevIconsUnicodeDecorateFileNodesPatternSymbols: "WebDevIconsUnicodeDecorateFileNodesPatternSymbols",
  fzfPreviewCommand: "fzf_preview_command",
  fzfBinaryPreviewCommand: "fzf_binary_preview_command",
  fzfPreviewIfBinaryCommand: "fzf_preview_if_binary_command",
  fzfPreviewFilelistCommand: "fzf_preview_filelist_command",
  fzfPreviewGitFilesCommand: "fzf_preview_git_files_command",
  fzfPreviewDirectoryFilesCommand: "fzf_preview_directory_files_command",
  fzfPreviewGitStatusCommand: "fzf_preview_git_status_command",
  fzfPreviewGitStatusPreviewCommand: "fzf_preview_git_status_preview_command",
  fzfPreviewGrepCmd: "fzf_preview_grep_cmd",
  fzfPreviewScriptDir: "fzf_preview_script_dir",
  fzfPreviewCacheDirectory: "fzf_preview_cache_directory",
  fzfPreviewLinesCommand: "fzf_preview_lines_command",
  fzfPreviewGrepPreviewCmd: "fzf_preview_grep_preview_cmd",
  fzfPreviewCustomProcesses: "fzf_preview_custom_processes",
  fzfPreviewFzfPreviewWindowOption: "fzf_preview_fzf_preview_window_option",
  fzfPreviewPreviewKeyBindings: "fzf_preview_preview_key_bindings",
  fzfPreviewFzfColorOption: "fzf_preview_fzf_color_option",
  fzfPreviewBuffersJump: "fzf_preview_buffers_jump",
  yankroundDir: "yankround_dir",
  fzfPreviewYankroundPreviewCommand: "fzf_preview_yankround_preview_command",
  fzfPreviewBlamePrCommand: "fzf_preview_blame_pr_command",
} as const

export const vimOptions = ["columns"] as const
